[package]
name = "raiden"
version = "0.1.0"
authors = ["Rakan Alhneiti <rakan.alhneiti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ethsign = "0.7.3"
ethabi = "13.0.0"
derive_more = "0.99.11"
futures = "0.3.12"
rpassword = "5.0.0"
rusqlite = "0.24.2"
serde = "1.0.119"
serde_json = "1.0.59"
slog = "2.7.0"
slog-async = "2.6.0"
slog-term = "2.6.0"
tokio = { version = "0.2", features = ["full"] }
web3 = "0.15.0"
ulid = "0.4.1"
url = "2.2.0"
